sources:
  - name: magic-pixels
    handler:
      graphql: 
        endpoint: https://gateway-arbitrum.network.thegraph.com/api/66f60fa965ddfb22b14e78b847a0770e/subgraphs/id/6VhWxDsd9jXrCKoCzszP9FFUUGcGhrvEYKQXfV6Ha1Fp # https://api.studio.thegraph.com/query/58444/magic-pixels-arbitrum/version/latest
    transforms: 
      - autoPagination:
          validateSchema: true
          limitOfRecords: 100
documents:
  - ./queries/pixels.graphql
  - ./queries/trades.graphql