sources:
  - name: magic-pixels
    handler:
      graphql: 
        endpoint: https://gateway-arbitrum.network.thegraph.com/api/66f60fa965ddfb22b14e78b847a0770e/subgraphs/id/BYGr9wEMdefE2SAPHqUXwYsLxzBCPxJjCwqpnocMxdhY
documents:
  - ./queries/pixels.graphql
  - ./queries/trades.graphql