sources:
  - name: magic-pixels
    handler:
      graphql: 
        endpoint: https://api.studio.thegraph.com/query/58444/magic-pixels-polygon/version/latest
documents:
  - ./queries/pixels.graphql
  - ./queries/trades.graphql